apiVersion: v1
kind: Service
metadata:
  name: agromarket-frontend-service
spec:
  selector:
    app: agromarket-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

