apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agromarket-uploads-pvc
  namespace: agromarket
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

