apiVersion: v1
kind: Secret
metadata:
  name: agromarket-secrets
type: Opaque
stringData:
  jwt_secret: "REPLACE_WITH_BASE64_OR_STRINGDATA_VALUE"
  db_password: "REPLACE_WITH_BASE64_OR_STRINGDATA_VALUE"
  db_username: "agromarket_user"
  jdbc_url: "jdbc:mysql://mysql:3306/agromarket_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  google_client_id: ""
  google_client_secret: ""

